<a href="https://colab.research.google.com/github/stardust453/learning-notebooks/blob/learning-notebooks-branch/Tensors_in_pytorch_notes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import torch
# print(torch.__version__)------------------------------------------------------
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
# if torch.cuda.is_available():
#     print("GPU is available!")
#     print(f"Using GPU: {torch.cuda.get_device_name(0)}")
# else:
#     print("GPU not available. Using CPU.")
if torch.cuda.is_available():
  print("GPU available using that")
  print(f"Using GPU named", torch.cuda.get_device_name(0))
else:
  print("GPU not avilable using CPU only")

GPU available using that
Using GPU named Tesla T4


## Creating a Tensor

In [4]:
# # using empty
# a = torch.empty(2,3)
a= torch.empty(3,4)
a, type(a), a.shape

(tensor([[2.1715e-18, 8.3894e-07, 2.6226e-09, 2.7599e-06],
         [1.0386e+21, 5.3175e-08, 8.4573e+20, 5.3834e+22],
         [5.4171e-05, 1.7392e-04, 2.1707e-18, 1.6678e+19]]),
 torch.Tensor,
 torch.Size([3, 4]))

In [5]:
# # using zeros
# torch.zeros(2,3)
b = torch.zeros(3,4)
b, type(b), b.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Tensor,
 torch.Size([3, 4]))

In [6]:
# using ones
c = torch.ones(2,3)
c, type(c), c.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Tensor,
 torch.Size([2, 3]))

In [9]:
# using rand
torch.rand(3,4,2)

tensor([[[0.7077, 0.4663],
         [0.4772, 0.3772],
         [0.6278, 0.0341],
         [0.2088, 0.1626]],

        [[0.7606, 0.5954],
         [0.0796, 0.0558],
         [0.3220, 0.3857],
         [0.5189, 0.4903]],

        [[0.8605, 0.6005],
         [0.4732, 0.0292],
         [0.5737, 0.1999],
         [0.7137, 0.9662]]])

In [10]:
# use of seed
torch.rand(2,3)

tensor([[0.3288, 0.8370, 0.1811],
        [0.4629, 0.0055, 0.7051]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[    139883306388912,     139883306388912,                   0],
        [                  0,                   0, 7310593858020254331]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
# torch.rand_like(x, dtype=torch.float32)
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Types

In [24]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9594, 0.1334],
        [0.8591, 0.6639]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9205, 0.0178],
        [0.7380, 0.4408]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0554, 0.7498, 0.3761],
        [0.6721, 0.5572, 0.2686]])
tensor([[0.3466, 0.1875, 0.7433],
        [0.6713, 0.9844, 0.0096]])


In [26]:
# add
a + b,  # Performs element-wise addition between tensors `a` and `b`.
# sub
a - b,  # Performs element-wise subtraction between tensors `a` and `b`.
# multiply
a * b,  # Performs element-wise multiplication between tensors `a` and `b`.
# division
a / b,  # Performs element-wise division between tensors `a` and `b`.
# power
a ** b, # Performs element-wise exponentiation between tensors `a` and `b`.
# mod
a % b   # Performs element-wise modulo operation between tensors `a` and `b`.

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),)

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [34]:
# clamp

torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [62]:
e = torch.randint(size=(3,2), low=1, high=10, dtype=torch.float32)
e

tensor([[6., 1.],
        [3., 1.],
        [3., 9.]])

In [54]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

torch.sum(e), torch.sum(e, dim=0), torch.sum(e, dim=1)

(tensor(34.), tensor([19., 15.]), tensor([15., 11.,  8.]))

In [55]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6.3333, 5.0000])

In [56]:
# median
torch.median(e)

tensor(6.)

In [57]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [58]:
# product
torch.prod(e)

tensor(9072.)

In [59]:
# standard deviation
torch.std(e)

tensor(3.0768)

In [60]:
# variance
torch.var(e)

tensor(9.4667)

In [63]:
# argmax
torch.argmax(e)

tensor(5)

In [64]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [65]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 2, 1],
        [0, 8, 3]])
tensor([[5, 0],
        [5, 8],
        [4, 9]])


In [66]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[34, 25],
        [52, 91]])

In [67]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [68]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 0],
        [2, 8],
        [1, 3]])

In [69]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 6., 1.],
        [5., 0., 7.],
        [5., 1., 0.]])

In [70]:
# determinant
torch.det(h)

tensor(173.)

In [72]:
# inverse
torch.pinverse(h),torch.inverse(h)

(tensor([[-0.0405,  0.0058,  0.2428],
         [ 0.2023, -0.0289, -0.2139],
         [ 0.0289,  0.1387, -0.1734]]),
 tensor([[-0.0405,  0.0058,  0.2428],
         [ 0.2023, -0.0289, -0.2139],
         [ 0.0289,  0.1387, -0.1734]]))

### 5. Comparison operations

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 6, 4],
        [3, 4, 3]])
tensor([[8, 8, 8],
        [8, 2, 9]])


In [74]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special functions

In [75]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 7., 7.],
        [3., 3., 2.]])

In [76]:
# log
torch.log(k)

tensor([[1.3863, 1.9459, 1.9459],
        [1.0986, 1.0986, 0.6931]])

In [78]:
# exp
torch.exp(k)

tensor([[  54.5981, 1096.6332, 1096.6332],
        [  20.0855,   20.0855,    7.3891]])

In [79]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.6458, 2.6458],
        [1.7321, 1.7321, 1.4142]])

In [83]:
# sigmoid
torch.sigmoid(k),k

(tensor([[0.9820, 0.9991, 0.9991],
         [0.9526, 0.9526, 0.8808]]),
 tensor([[4., 7., 7.],
         [3., 3., 2.]]))

In [84]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.9820, 0.9933],
        [0.2689, 0.0180, 0.0067]])

In [85]:
# relu
torch.relu(k)

tensor([[4., 7., 7.],
        [3., 3., 2.]])

## Inplace Operations

In [86]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8165, 0.4348, 0.6186],
        [0.7956, 0.1282, 0.4270]])
tensor([[0.2543, 0.6202, 0.1659],
        [0.7134, 0.0013, 0.4804]])


In [89]:
m.add_(n) #equivalent to m = m + n

tensor([[1.3252, 1.6751, 0.9505],
        [2.2224, 0.1308, 1.3878]])

In [90]:
m

tensor([[1.3252, 1.6751, 0.9505],
        [2.2224, 0.1308, 1.3878]])

In [91]:
n

tensor([[0.2543, 0.6202, 0.1659],
        [0.7134, 0.0013, 0.4804]])

In [92]:
torch.relu(m)

tensor([[1.3252, 1.6751, 0.9505],
        [2.2224, 0.1308, 1.3878]])

In [93]:
m.relu_()

tensor([[1.3252, 1.6751, 0.9505],
        [2.2224, 0.1308, 1.3878]])

In [94]:
m

tensor([[1.3252, 1.6751, 0.9505],
        [2.2224, 0.1308, 1.3878]])

## Copying a Tensor

In [95]:
a = torch.rand(2,3)
a

tensor([[0.3427, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [96]:
b = a

In [97]:
b

tensor([[0.3427, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [98]:
a[0][0] = 0

In [99]:
a

tensor([[0.0000, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [100]:
b

tensor([[0.0000, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [101]:
id(a)

139878635529104

In [102]:
id(b)

139878635529104

In [106]:
b = a.clone() #now changing b wont change a as we made a clone of a

In [107]:
a

tensor([[0.0000, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [108]:
b

tensor([[0.0000, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [109]:
a[0][0] = 10

In [110]:
a

tensor([[10.0000,  0.3037,  0.9663],
        [ 0.9853,  0.9767,  0.9520]])

In [111]:
b

tensor([[0.0000, 0.3037, 0.9663],
        [0.9853, 0.9767, 0.9520]])

In [112]:
id(a)

139878635529104

In [113]:
id(b)

139878635529296